theme: jekyll-theme-cayman

# NOTE: 
# remote_theme: is always prefered and loaded before theme: no matter where it is placed in this .yml file.
# There is no need to clear Chrome browser's cache for the remote_theme: or theme: to give an effect, 
# just wait a few seconds after any commit that changes style hosted in remote_theme:

# any changes commited to remote_theme:
# might take up to 40 seconds after the commit to _config.yml, for the changes to be seen.
#remote_theme: benbalter/retlab

# For the changes in the layout of remote_theme: to show up, there is need to switch back to theme:
# and then switch back to remote_theme:
#
#
remote_theme: WebCitation/retlab


#No changes appear in the github page after remote_theme: repository is deleted.
#No changes appear in the github page after remote_theme: repository is forked again.

#Updating _config.yml without commenting remote_theme: and reenabling theme:
#then later uncommenting remote_theme: the changes won't be seen.

#After commenting remote_theme: 
# The Changes quickly began show up: 
# The reforked repository's theme suddenly showed up
# then later the theme: has been set
